essay_grader/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('grader_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

grader_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("create", views.create, name="create"),
    path("setup", views.setup, name="setup"),
    path("home", views.index, name="home"),
    path("<int:pk>/", views.detail, name="detail"),
    path("submit", views.submit, name="submit"),
    path("dark_mode/", views.dark, name="dark_mode"),
    path('ajax/load-assignments/', views.load_assignments, name='ajax_load_assignments'),
    path('ajax/load-essay/', views.load_essay, name="ajax_load_essay"),
    path('ajax/validate/', views.validate_due_date, name="ajax_validate"),
    path('ajax/User/email', views.validate_user_email, name="ajax_user_email"),
    path('ajax/User/password', views.validate_user_password, name="ajax_user_password"),
    path('teacher/ajax/comment/', views.comment, name="ajax_comment"),
    path("teacher/home", views.teacher, name="teacher"),
    path("teacher/assignment", views.assignment, name="assignment"),
    path("teacher/<int:pk>/graded", views.teacher_graded, name="teacher_graded"),
    path("teacher/<int:pk>/not_graded", views.teacher_not_graded, name="teacher_not_graded"),
    path("teacher/<int:pk>/grade", views.grade, name="grade"),
    path("teacher/<int:pk>/grade_essay", views.grade_essay, name="grade_essay"),
    path("settings/info", views.settings_changeInfo, name="settings_info"),
    path("settings/password", views.settings_changePassword, name="settings_password"),
    path("settings/teachers", views.settings_changeTeachers, name="settings_teachers"),
]

grader_app/models.py
import json

from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.db import models


# Create your models here.
class Comment(models.Model):
    author = models.ForeignKey('User', on_delete=models.CASCADE)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    essay = models.ForeignKey('Essay', on_delete=models.CASCADE)


class Assignment(models.Model):
    assignment_name = models.CharField(max_length=150, blank=False)
    assignment_description = models.TextField()
    due_date = models.CharField(max_length=19)

    def __str__(self):
        return self.assignment_name


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_studentuser(self, email, password):
        user = self.create_user(
            email,
            password=password,
        )
        user.student = True
        user.save(using=self._db)
        return user

    def create_teacheruser(self, email, password):
        user = self.create_user(
            email,
            password=password,
        )
        user.teacher = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(
            email,
            password=password,
        )
        user.teacher = True
        user.admin = True
        user.student = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, null=True)
    last_name = models.CharField(max_length=50)
    logged_with_ion = models.BooleanField(default=False)
    dark_mode = models.BooleanField(default=False)

    teachers = models.TextField(default=json.dumps({
        "period_1_teacher": "",
        "period_2_teacher": "",
        "period_3_teacher": "",
        "period_4_teacher": "",
        "period_5_teacher": "",
        "period_6_teacher": "",
        "period_7_teacher": "",
    }))

    def set_teachers(self, teacher):
        self.teachers = json.dumps(teacher)
        self.save()

    def get_teachers(self):
        return json.loads(self.teachers)

    assignments = models.ManyToManyField(Assignment)

    FRESHMAN = 'FR'
    SOPHOMORE = 'SO'
    JUNIOR = 'JR'
    SENIOR = 'SR'
    GRADUATE = 'GR'

    YEAR_IN_SCHOOL_CHOICES = [
        (FRESHMAN, 'Freshman'),
        (SOPHOMORE, 'Sophomore'),
        (JUNIOR, 'Junior'),
        (SENIOR, 'Senior'),
        (GRADUATE, 'Graduate'),
    ]
    year_in_school = models.CharField(
        max_length=2,
        choices=YEAR_IN_SCHOOL_CHOICES,
        default=FRESHMAN,
    )
    student = models.BooleanField(default=False)
    teacher = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def username(self):
        return "%s %s" % (self.first_name, self.last_name)

    def get_identification(self):
        return self.email

    def get_email(self):
        return self.email

    def get_full_name(self):
        return "%s %s" % (self.first_name, self.last_name)

    def get_short_name(self):
        return self.first_name

    def get_grade(self):
        return self.year_in_school

    def __str__(self):
        return self.get_full_name()

    @staticmethod
    def has_perm(perm, obj=None):
        return True

    @staticmethod
    def has_module_perms(app_label):
        return True

    @property
    def is_student(self):
        return self.student

    @property
    def is_staff(self):
        return self.teacher

    @property
    def is_admin(self):
        return self.admin

    objects = UserManager()


class Essay(models.Model):
    dropdown = (("APA", "APA"), ("MLA", "MLA"))
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="author")
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE, related_name="teacher", null=True)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=500)
    body = models.TextField()
    raw_body = models.TextField(default="")
    created_on = models.DateTimeField(auto_now_add=True)
    citation_type = models.CharField(max_length=150, choices=dropdown, default="None")
    marked_body = models.TextField(default="")
    graded = models.BooleanField(default=False)
    marked = models.BooleanField(default=False)
    grade_numerator = models.IntegerField(default=0)
    grade_denominator = models.IntegerField(default=0)

grader_app/views.py
import datetime
import email.message
import email.message
import json
import smtplib
import re
import pytz
from django import forms
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect
from requests_oauthlib import OAuth2Session
from .forms import EssayForm, LoginForm, InfoForm, ChangeForm, TeacherForm, AssignmentForm, \
    CommentForm, RegisterForm, SetupForm
from .models import Essay, Assignment, Comment
from .models import User
from .tasks import grade_all
from html import unescape
from unicodedata import normalize
from celery.result import ResultBase


# Create your views here.

# noinspection PyUnresolvedReferences
def login(request):
    admins = {"2023avasanth", "2023pbhandar", "2023kbhargav"}

    if request.user is not None and request.user.is_authenticated:
        return redirect("home")

    context = {
        'url': 'login'
    }
    client_id = "FeZBHle5SNytiEwAh333mPmoEmfFDQSF1Jigy2bW"
    client_secret = "saNPOvrrCGhNK1TywLjTsKo3M5uFzfQEgUtTpvvZsNIQPB75eeWYqhBxYMZJb0lKG5LZRZx" \
                    "1ZVN7ZUEiUUUqPeE8GMH0ZwdhbG4yNKKYmcCDu0UXV2gopeUB3B4cAIzw"
    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            mail_id = form.cleaned_data["email"]
            if User.objects.filter(email=mail_id).exists():
                user = auth.authenticate(email=mail_id, password=form.cleaned_data["password"])
                if user is not None:
                    auth.login(request, user)
                    return redirect("home")
            else:
                form = LoginForm()
                context['form'] = form

            context['error'] = "Username or Password is incorrect"
        else:
            form = LoginForm()
            context['form'] = form

    elif request.method == "GET" or request.user is None:
        form = LoginForm()
        context['form'] = form
        oauth = OAuth2Session(client_id,
                              redirect_uri="http://essay-grader.sites.tjhsst.edu/login",
                              scope=["read"])
        authorization_url, state = oauth.authorization_url("https://ion.tjhsst.edu/oauth/authorize/")
        context['url'] = authorization_url
        if "code" in request.GET:
            CODE = request.GET.get("code")

            oauth.fetch_token("https://ion.tjhsst.edu/oauth/token/",
                              code=CODE,
                              client_secret=client_secret)

            try:
                raw_profile = oauth.get("https://ion.tjhsst.edu/api/profile")
                profile = json.loads(raw_profile.content.decode())
                mail_id = profile["tj_email"]
                if User.objects.filter(email=mail_id).exists():
                    user = auth.authenticate(email=mail_id,
                                             password=profile.get("ion_username") + profile.get("user_type"))
                    if user is not None:
                        auth.login(request, user)
                        user = request.user
                        user.logged_with_ion = True
                        user.save()
                        return redirect("home")

                else:
                    if profile.get("ion_username") in admins or profile.get("is_eighth_admin"):
                        new_user = User.objects.create_superuser(email=mail_id,
                                                                 password=profile.get("ion_username") + profile.get(
                                                                     "user_type"))
                    elif profile.get("is_teacher"):
                        new_user = User.objects.create_teacheruser(email=mail_id,
                                                                   password=profile.get("ion_username") + profile.get(
                                                                       "user_type"))
                    else:
                        new_user = User.objects.create_studentuser(email=mail_id,
                                                                   password=profile.get("ion_username") + profile.get(
                                                                       "user_type"))
                    new_user.logged_with_ion = True
                    new_user.first_name = profile.get("first_name")
                    new_user.middle_name = profile.get("middle_name")
                    new_user.last_name = profile.get("last_name")
                    new_user.year_in_school = profile.get("grade").get("name").upper()[:3]
                    new_user.save()
                    user = auth.authenticate(email=mail_id,
                                             password=profile.get("ion_username") + profile.get("user_type"))
                    auth.login(request, user)
                    return redirect("home")

            except Exception as e:
                context['error'] = str(e)
                args = {"client_id": client_id, "client_secret": client_secret}
                oauth.refresh_token("https://ion.tjhsst.edu/oauth/token/", **args)
    return render(request, "login.html", context)


def logout(request):
    auth.logout(request)
    return redirect("home")


def create(request):
    if request.user.is_authenticated:
        return redirect("home")
    context = {"method": request.method}
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            error = False
            mail = password = ""
            try:
                mail = form.cleaned_data.get('email')
                qs = User.objects.filter(email=mail)
                if qs.exists():
                    raise forms.ValidationError("email is taken")
            except forms.ValidationError:
                error = True

            try:
                password = form.clean_password2()
                if len(password) < 8:
                    raise ValueError
            except forms.ValidationError:
                error = True
            except ValueError:
                error = True

            specs = '!"#$%&\'()*+,-./:;<=>?@[\]^_`{|}~'
            numbers = "0123456789"
            special = False
            for char in specs:
                special = special or password.__contains__(char)
            number = False
            for char in numbers:
                number = number or password.__contains__(char)
            upper = False
            lower = False
            for char in password:
                if char.lower() == char:
                    lower = True
                else:
                    upper = True
            upandlow = lower and upper

            if not error and upandlow and number and special:
                new_user = User.objects.create_studentuser(email=mail, password=password)
                new_user.save()
                user = auth.authenticate(email=mail, password=password)
                auth.login(request, user)
                return redirect("setup")
            else:
                form = RegisterForm()
                context['form'] = form
        else:
            form = RegisterForm()
            context['form'] = form

    else:
        form = RegisterForm()
        context['form'] = form
    return render(request, "create.html", context)


def setup(request):
    context = {
        "method": request.method,
        "form": SetupForm()
    }
    if context['method'] == "POST":
        form = SetupForm(request.POST)
        if form.is_valid():
            user = request.user
            user.first_name = form.cleaned_data.get('first_name')
            user.middle_name = form.cleaned_data.get('middle_name')
            user.last_name = form.cleaned_data.get('last_name')
            user.year_in_school = form.cleaned_data.get('year_in_school')
            user.save()
            return redirect("home")
    return render(request, "setup.html", context)


def index(request):
    if request.user.is_authenticated:
        essays = []
        query = ""

        if request.GET:
            query = request.GET.get('q', 'Search for an essay')

        if query != "":
            profile = request.user
            queryset = []
            queries = query.split(" ")

            for q in queries:
                essays = Essay.objects.filter(author=profile).filter(
                    Q(title__icontains=q) |
                    Q(body__icontains=q)
                ).order_by('-created_on').distinct()

                for essay in essays:
                    queryset.append(essay)

            essays = list(set(queryset))

        if request.user.teacher and not request.user.admin:
            return redirect("teacher")

        if not essays:
            essays = Essay.objects.all().filter(author=request.user).order_by('-created_on')

        context = {
            "essays": essays,
            "query": str(query),
            "search": query != ""
        }

        return render(request, "index.html", context)

    else:
        return render(request, "index.html")


@login_required(login_url="login")
def submit(request):
    form = EssayForm(request.POST or None, **{'user': request.user})
    if request.method == 'POST':

        if form.is_valid():
            data = format_body(form.data["body"])
            essay = Essay(
                title=form.cleaned_data["title"],
                body=form.data["body"],
                author=request.user,
                assignment=form.cleaned_data["assignment"],
                teacher=User.objects.get(email=form.cleaned_data["teachers"]),
                citation_type=form.cleaned_data["citation_type"],
                marked_body=data,
                raw_body=data,
            )
            essay.save()

grader_app/templates/assignment.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/assignment.css' %}"/>
{% endblock %}

{% block content %}
    <!------------ Assignment Creation ------------->
    {% if user.is_authenticated %}
    <div class="col-md-8 offset-md-2 body">

        <h3>Add an Assignment:</h3>
        <!-- Assignment Form -->
        <form action="{% url 'assignment' %}" method="post">
            {% csrf_token %}
            <br>
            {{ form.as_p }}

            <label>Assignment Due Date</label>
            <!-- Calendar DateTime input -->
            <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1" name="due_date" required id="id_due_date"/>
                <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                    <div class="input-group-text">
                        <i class="fa fa-calendar"></i>
                    </div>
                </div>
            </div>

            <br>

            <div class="submit">
                <button type="submit" id="btn" class="btn btn-primary" onclick="interval()" value="{{ next }}">
                    Add Assignment
                </button>
            </div>

        </form>

    </div>
    {% else %}
    <h3>You must be logged in to view this page.</h3>
    {% endif %}
{% endblock %}

grader_app/templates/create.html
{% extends "base.html" %}
{% load static %}
{% block css %}
	<link href="{% static 'css/login.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block content %}
<!------------ Create User Account ------------->
<div class="col-md-8 offset-md-2 box bg-light content" style="width: 60% !important; left: 20% !important;">
    <h2>
		<center>
			Create Account
		</center>
	</h2>

	<!-- Errors -->

	<h6 class="error" id="error">{% if method == "POST" %}Your account is invalid.{% endif %}</h6>

	<!-- User Creation Form -->
	<form action="{% url 'create' %}" method="post" style="width: 45% !important;">
		{% csrf_token %}
		{{ form.as_p }}
		<div class="button-holder" >
			<button type="submit" class="btn btn-primary" onclick="interval()" id="btn" value="{{ next }}">
				Submit
			</button>
		</div>
	</form>

	<!-- Checkboxes -->
	<div style="float: right;display: inline-block; text-align: left; vertical-align: top; width: 45%; font-size: 10;">
		<info id="imgs" x="{% static 'img/x.png' %}" check="{% static 'img/check.png' %}"></info>
		<br>
		<img id="a" src="{% static 'img/x.png' %}" width="10px" height="10px"> Valid Email <br><br>
		<img id="b" src="{% static 'img/x.png' %}" width="10px" height="10px"> Password is 8 characters in length <br><br>
		<img id="c" src="{% static 'img/x.png' %}" width="10px" height="10px"> Password contains special character <br><br>
		<img id="d" src="{% static 'img/x.png' %}" width="10px" height="10px"> Password contains number <br><br>
		<img id="e" src="{% static 'img/x.png' %}" width="10px" height="10px"> Password contains upper and lower letters<br><br>
		<img id="f" src="{% static 'img/x.png' %}" width="10px" height="10px"> Passwords match
	</div>


</div>
<script language="JavaScript">
	$("#id_email").change(checkEmail());
	window.setInterval(checkEmail, 600);
	window.setInterval(checkPassword, 600);
	function checkEmail() {
		console.log("Checking Email");
		var value = document.getElementById("id_email").value;
		$.ajax({
			url: "/ajax/User/email",
			data: {
			 	'email': value
			},
			success: function (data) {
				if (data.valid){
			 		document.getElementById("a").src = document.getElementById("imgs").getAttribute("check");
			 	} else {
			 		document.getElementById("a").src = document.getElementById("imgs").getAttribute("x");
			 	}
		    }
		});
	}
	function checkPassword() {
		console.log("Checking Password");
		var password1 = document.getElementById("id_password").value;
		var password2 = document.getElementById("id_password2").value;
		$.ajax({
			url: "/ajax/User/password",
			data: {
			 	'password1': password1,
			 	'password2': password2
			},
			success: function (data) {
				if (data.length){
			 		document.getElementById("b").src = document.getElementById("imgs").getAttribute("check");
				} else {
			 		document.getElementById("b").src = document.getElementById("imgs").getAttribute("x");
				}
				if (data.special){
			 		document.getElementById("c").src = document.getElementById("imgs").getAttribute("check");
				} else {
			 		document.getElementById("c").src = document.getElementById("imgs").getAttribute("x");
				}
				if (data.number){
			 		document.getElementById("d").src = document.getElementById("imgs").getAttribute("check");
				} else {
			 		document.getElementById("d").src = document.getElementById("imgs").getAttribute("x");
				}
				if (data.upandlow){
			 		document.getElementById("e").src = document.getElementById("imgs").getAttribute("check");
				} else {
			 		document.getElementById("e").src = document.getElementById("imgs").getAttribute("x");
				}
				if (data.match){
			 		document.getElementById("f").src = document.getElementById("imgs").getAttribute("check");
				} else {
			 		document.getElementById("f").src = document.getElementById("imgs").getAttribute("x");
				}
		    }
		});
	}
</script>
{% endblock %}

grader_app/templates/detail.html
{% extends "base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/detail.css' %}"/>
{% endblock %}
{% block content %}
    <!------------ Essay Detailed ------------->
    {% if user.is_authenticated %}
    <div class="col-md-8 offset-md-2 detail">
        <h1>Essay</h1>
        <hr>
        <!-- Essay Information -->
        <h2>{{ essay.title }}</h2>
        <h5> Assignment: {{essay.assignment}}</h5>
        <h5> By: {{essay.author.get_full_name}} </h5>
        <h5> For: {{essay.teacher.get_full_name}} </h5>
        <h6> Created on {{ essay.created_on }}</h6>
        <p>{{ essay.raw_body | safe | linebreaks}}</p>
        <hr>
        <!-- Comments -->
        {% for comment in comments %}
            <div class="comment">
            <h6 class="author">{{comment.author.get_full_name}}</h6>
            <h6 class="date">{{comment.created_on}}</h6>
            <p>{{comment.body}}</p>
            </div>
        {% endfor %}
        <!-- Comment Form -->
        <form action="{% url 'detail' essay.pk%}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button id="btn" onclick="interval()" type="submit" class="btn btn-primary" value="{{ next }}">
                Comment
            </button>
        </form>
    </div>
    {% else %}
        <h4 class="error">You are not logged in. Please log in to submit or view your essays.</h4>
    {% endif %}
{% endblock %}

grader_app/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}"/>
{% endblock %}
<!------------ Student Index Interface ------------->
{% block content %}
    {% if user.is_authenticated and user.student %}
        <!-- Search Bar -->
    
        <div class="wrapper">
            <div class="search-bar mt-sm-2 mr-2 offset-md-2 col-md-8">
                <form method="get">
                    <input type="text" class="form-control" name="q" id="id_q" query="{{ query }}" placeholder="Search for Essay"/>
                </form>
            </div>
        </div>

        <!-- Error Messages -->

        <div class="col-md-8 offset-md-2 index">
            <h1>Essays</h1>
            <hr>
                {% if essays|length == 0 %}
                    {% if search == False %}
                        <h3>No essays yet, why don't you submit one?</h3>
                    {% else %}
                        <h3>No results based on your search</h3>
                    {% endif %}
                {% endif %}

            <!-- All Essays Created by student -->

                {% for essay in essays %}
                    <h2>
                        <a href="{% url 'detail' essay.pk%}" class="title">
                            {{ essay.title }}
                        </a>
                        <a class="grade">
                            {% if essay.graded %}{{essay.grade_numerator}}/{{essay.grade_denominator}}{% endif%}
                        </a>
                    </h2>
                    <!-- Essay Information -->
                    <h5> Assignment: {{essay.assignment}}</h5>
                    <h5> By: {{essay.author}}</h5>
                    <h5> For: {{essay.teacher}}</h5>
                    <h6> Created on {{ essay.created_on }}
                        {% if essay.citation_type != "None" %}
                        <b class="grade">Type: {{essay.citation_type}}</b>
                        {% endif %}
                    </h6>
                    <hr>
                {% endfor %}
        </div>
    {% else %}
        <div class="col-md-8 offset-md-2 index">
            <h1 style="padding-bottom: 1%;">Essay Grader</h1>
            <h5>This website speeds up essay grading by automating the objective parts of essay grading.</h6>
            <hr>
            <h3 style="padding-top: 1%; padding-bottom: 1%;">How do I use this?</h3>
            <h5>Students</h5>
            <p>If you're a student, log in (logging in with Ion is preferred) and add your teachers that use this website in settings. 
                Once your teacher has added an assignment, you can submit in essay via the submit portal. 
                When submitting, you don't have to use the rich text editor if you don't want to; you can 
                just create in Google Docs or Word and copy and paste it in, and it should keep the formatting 
                (double check your essay to make sure, though, because it might not keep all of the formatting).
                You will get notified via email once your teacher has graded your essay, and you can check the status 
                of your submitted essays from the home page. You can also check for feedback on your essay by clicking on 
                the essay title, and you will see if your teacher left any comments on your essay.</p>
            <h5>Teachers</h5>
            <p>
                If you're a teacher, log in <strong>(teachers must log in using Ion to ensure authenticity)</strong> and add an assignment, so that your students can start submitting essays. 
                To grade essays, head over to the Grade tab, where you can see all of the submitted essays for an assignment and grade them.
                When grading essays, essays can be one of three things: not marked, marked, or graded. 
            </p> 

            <p>
                Marking refers to whether or not the essay has been checked by our system for spelling/grammar, plagiarism, and citation checking.
                <strong>The marking process will not work properly if an essay does not have a References or Works Cited section; this website should not be used to grade essays without citations and a reference list.</strong>
                After an essay is marked, you will see a plagiarism report above the body of the essay.
                Plagiarism is determined as a score from 0 to 1 by the <a href="https://en.wikipedia.org/wiki/Jaccard_index" target="_blank" rel="noopener noreferrer">Jaccard Similarity</a> 
                between the words in two essays, and each essay is compared with all other submitted essays in that assignment. 
                After marking, each essay's body will also be highlighted with red text where there are any spelling/grammar mistakes,
                and the citations will be marked for correctness, cross-referenced to ensure that every citation is cited as an 
                in-text citation, and checked for alphabetical order. When checking citations using the APA format, warnings will 
                appear with all capitalized words (other than the first word) in the title, as we are currently unable to check if a word should be capitalized 
                in sentence case due to the extensive Natural Language Processing and computing power required. Note: the marking process is not perfect, and a citation
                can be falsely marked as incorrect (although this happens rarely), so please check the errors before grading. To mark all of the submitted essays, click the Mark All button at the bottom of the Grade tab. 
            </p>

            <p>
                After marking essays, you can manually grade the essays (for subjective factors, such as style, content, etc.) and enter the score 
                in the top right hand corner of the Grade tab. You can also leave feedback for your students by entering a comment.
            </p>
        </div>
    {% endif %}
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/index.js' %}" language="JavaScript"></script>
{% endblock %}

grader_app/templates/load_essay.html
<!-- Essay in Full View -->
<h2 id="Title" style="display:inline-block;">{{ essay.title }}</h2>
<div style="float:right;">
    <!-- Grading form -->
    {% if essay.grade_denominator == 0 %}
        <h2 style="float:right; margin-right:20px;">
            <input type="text" class="form-control" name="numerator" id="numerator" style="display:inline-block; width:60px;">
            <b>/</b>
            <input type="text" class="form-control" name="denominator" id="denominator" style="display:inline-block;width:60px;">
        </h2>
        <h3>
            <button value="{{ essay.pk }}" pk="{{essay.pk}}" url="{% url 'grade_essay' essay.pk %}" style="float:right; margin:25px;" class="btn btn-primary" type="submit" id="add_grade" onclick="gradeEssay()">Grade This Essay</button>
        </h3>
    {% else %}
        <h2 style="float:right; margin-right:20px;">{{essay.grade_numerator}}<b>/</b>{{essay.grade_denominator}}</h2>
    {% endif %}
</div>
<!-- Essay Details -->
<h3 id="Author">{{ essay.author.get_full_name }}</h3>
<h4 id="Created">{{ essay.created_on }}</h4><br>
{% if essay.marked %} <p id="Body">{{ essay.marked_body | safe}}</p> {% else %} <p id="Body">{{ essay.body | safe}}</p> {% endif %}
<hr>
<br>
<!-- Comments -->
{% for comment in comments %}
    <div class="comment">
    <h6 style="display: inline-block;">{{comment.author.get_full_name}}</h6>
    <h6 style="display:inlnie-block; float: right;">{{comment.created_on}}</h6>
    <p>{{comment.body}}</p>
    </div>
{% endfor %}
<!-- Comment Form -->
{{ form.as_p }}
<button id="btn" onclick="interval(); addComment({{essay.pk}})" class="btn btn-primary">
    Comment
</button>